sudo: false
language: node_js
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react babel-eslint
script:
  - eslint --ext .js,.jsx .
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
